name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout & node
        uses:
          actions/checkout@v2
          actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Set env
        run: echo "::set-env name=test_secret::${{secrets.TEST_SECRET}}"

      - name: npm run build
        run: |
          npm ci
          npm run build

      # - name: Get token
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
