name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          pwd

      # - name: Get token
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
